version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    build: .
    #command: sleep 10000000000000000000000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    volumes:
      - ./metabase:/metabase
    ports:
      - "3333:3000"
    env_file:
      - .metabase-env
    depends_on:
      - db
