# Generated by Django 4.2.9 on 2024-02-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('SSH', 'School of Sciences and Humanities'), ('SMG', 'School of Mining and Geosciences'), ('NUSOM', 'School of Medicine'), ('CPS', 'Center for Preparatory Studies'), ('GSE', 'Graduate School of Education'), ('GSB', 'Graduate School of Business'), ('GSPP', 'Graduate School of Public Policy'), ('SEDS', 'School of Engineering and Digital Sciences')], default='SEDS', max_length=50),
        ),
    ]
