# Generated by Django 4.2.9 on 2024-02-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('GSE', 'GSE | Graduate School of Education'), ('NUSOM', 'NUSOM | School of Medicine'), ('SSH', 'SSH | School of Sciences and Humanities'), ('GSPP', 'GSPP | Graduate School of Public Policy'), ('SEDS', 'SEDS | School of Engineering and Digital Sciences'), ('GSB', 'GSB | Graduate School of Business'), ('CPS', 'CPS | Center for Preparatory Studies'), ('SMG', 'SMG | School of Mining and Geosciences')], max_length=6, unique=True),
        ),
    ]
