# Generated by Django 4.2.9 on 2024-02-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0018_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('SMG', 'SMG | School of Mining and Geosciences'), ('NUSOM', 'NUSOM | School of Medicine'), ('SEDS', 'SEDS | School of Engineering and Digital Sciences'), ('SSH', 'SSH | School of Sciences and Humanities'), ('GSPP', 'GSPP | Graduate School of Public Policy'), ('CPS', 'CPS | Center for Preparatory Studies'), ('GSE', 'GSE | Graduate School of Education'), ('GSB', 'GSB | Graduate School of Business')], max_length=6, unique=True),
        ),
    ]
