# Generated by Django 4.2.9 on 2024-03-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0025_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('NUSOM', 'NUSOM | School of Medicine'), ('CPS', 'CPS | Center for Preparatory Studies'), ('GSB', 'GSB | Graduate School of Business'), ('SSH', 'SSH | School of Sciences and Humanities'), ('GSPP', 'GSPP | Graduate School of Public Policy'), ('SMG', 'SMG | School of Mining and Geosciences'), ('SEDS', 'SEDS | School of Engineering and Digital Sciences'), ('GSE', 'GSE | Graduate School of Education')], max_length=6, unique=True),
        ),
    ]
