# Generated by Django 4.2.9 on 2024-01-28 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegetting',
            name='grade_distribution',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('C-', 'C-'), ('B', 'B'), ('D', 'D'), ('B+', 'B+'), ('C+', 'C+'), ('D+', 'D+'), ('A-', 'A-'), ('P', 'P'), ('C', 'C'), ('NP', 'NP'), ('F', 'F'), ('B-', 'B-')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.AddField(
            model_name='coursegetting',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.section'),
        ),
    ]
