# Generated by Django 4.2.9 on 2024-01-28 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_department_name_and_more'),
        ('courses', '0003_alter_course_credits_alter_course_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('W', 'W'), ('D+', 'D+'), ('C+', 'C+'), ('C-', 'C-'), ('B+', 'B+'), ('B-', 'B-'), ('AU', 'AU'), ('A-', 'A-'), ('A', 'A'), ('B', 'B'), ('P', 'P'), ('F', 'F'), ('D', 'D'), ('C', 'C'), ('I', 'I')], default='A', max_length=2),
        ),
    ]
