# Generated by Django 4.2.9 on 2024-02-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_coursegetting_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_type',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('P', 'P'), ('AU', 'AU'), ('B-', 'B-'), ('F', 'F'), ('C', 'C'), ('I', 'I'), ('D+', 'D+'), ('B', 'B'), ('A-', 'A-'), ('W', 'W'), ('C-', 'C-'), ('D', 'D'), ('C+', 'C+')], default='A', max_length=2),
        ),
    ]
