# Generated by Django 4.2.9 on 2024-02-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_section_section_type_alter_coursegetting_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='capacity',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='section',
            name='enrolled',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('B', 'B'), ('D+', 'D+'), ('AU', 'AU'), ('B+', 'B+'), ('I', 'I'), ('C', 'C'), ('P', 'P'), ('C+', 'C+'), ('A', 'A'), ('B-', 'B-'), ('W', 'W'), ('A-', 'A-'), ('C-', 'C-'), ('D', 'D'), ('F', 'F')], default='A', max_length=2),
        ),
    ]
