# Generated by Django 4.2.9 on 2024-02-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0008_alter_department_name'),
        ('courses', '0011_alter_coursegetting_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('F', 'F'), ('C+', 'C+'), ('C', 'C'), ('P', 'P'), ('A', 'A'), ('I', 'I'), ('AU', 'AU'), ('A-', 'A-'), ('B-', 'B-'), ('D+', 'D+'), ('C-', 'C-'), ('B+', 'B+'), ('B', 'B'), ('D', 'D'), ('W', 'W')], default='A', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'department')},
        ),
    ]
