# Generated by Django 4.2.9 on 2024-02-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_name_alter_coursegetting_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('D+', 'D+'), ('B', 'B'), ('B-', 'B-'), ('F', 'F'), ('A-', 'A-'), ('A', 'A'), ('D', 'D'), ('W', 'W'), ('B+', 'B+'), ('C+', 'C+'), ('P', 'P'), ('AU', 'AU'), ('I', 'I'), ('C', 'C'), ('C-', 'C-')], default='A', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'section_number', 'section_type')},
        ),
    ]
