# Generated by Django 4.2.9 on 2024-02-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_coursegetting_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('P', 'P'), ('I', 'I'), ('B+', 'B+'), ('B', 'B'), ('A-', 'A-'), ('A', 'A'), ('D+', 'D+'), ('B-', 'B-'), ('F', 'F'), ('D', 'D'), ('C', 'C'), ('W', 'W'), ('AU', 'AU'), ('C+', 'C+'), ('C-', 'C-')], default='A', max_length=2),
        ),
    ]
