# Generated by Django 4.2.9 on 2024-02-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_course_name_alter_coursegetting_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('AU', 'AU'), ('W', 'W'), ('C+', 'C+'), ('A', 'A'), ('C', 'C'), ('B-', 'B-'), ('B', 'B'), ('I', 'I'), ('B+', 'B+'), ('P', 'P'), ('D+', 'D+'), ('F', 'F'), ('C-', 'C-'), ('D', 'D'), ('A-', 'A-')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
