# Generated by Django 4.2.9 on 2024-02-03 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_coursegetting_grade_alter_section_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.semester'),
        ),
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('P', 'P'), ('F', 'F'), ('A', 'A'), ('AU', 'AU'), ('B-', 'B-'), ('C-', 'C-'), ('D', 'D'), ('B', 'B'), ('C', 'C'), ('W', 'W'), ('B+', 'B+'), ('D+', 'D+'), ('I', 'I'), ('C+', 'C+'), ('A-', 'A-')], default='A', max_length=2),
        ),
    ]
