# Generated by Django 4.2.9 on 2024-02-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_semester_alter_coursegetting_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('B-', 'B-'), ('B+', 'B+'), ('C-', 'C-'), ('D+', 'D+'), ('B', 'B'), ('D', 'D'), ('C', 'C'), ('AU', 'AU'), ('I', 'I'), ('F', 'F'), ('C+', 'C+'), ('W', 'W'), ('A', 'A'), ('A-', 'A-'), ('P', 'P')], default='A', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'semester')},
        ),
    ]
