# Generated by Django 4.2.9 on 2024-02-04 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0019_alter_department_name'),
        ('courses', '0022_alter_coursegetting_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='Instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.instructor'),
        ),
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('I', 'I'), ('A-', 'A-'), ('B', 'B'), ('D+', 'D+'), ('P', 'P'), ('AU', 'AU'), ('D', 'D'), ('C+', 'C+'), ('F', 'F'), ('C-', 'C-'), ('A', 'A'), ('C', 'C'), ('B+', 'B+'), ('B-', 'B-'), ('W', 'W')], default='A', max_length=2),
        ),
    ]
