# Generated by Django 4.2.9 on 2024-02-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_section_instructor_alter_coursegetting_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='Instructor',
            new_name='instructor',
        ),
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('C-', 'C-'), ('P', 'P'), ('F', 'F'), ('I', 'I'), ('B+', 'B+'), ('B', 'B'), ('A', 'A'), ('W', 'W'), ('C+', 'C+'), ('D+', 'D+'), ('B-', 'B-'), ('AU', 'AU'), ('C', 'C'), ('A-', 'A-'), ('D', 'D')], default='A', max_length=2),
        ),
    ]
