# Generated by Django 4.2.9 on 2024-02-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0021_alter_department_name'),
        ('courses', '0024_rename_instructor_section_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='instructor',
        ),
        migrations.AddField(
            model_name='section',
            name='instructors',
            field=models.ManyToManyField(to='departments.instructor'),
        ),
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B-', 'B-'), ('AU', 'AU'), ('B+', 'B+'), ('F', 'F'), ('I', 'I'), ('C+', 'C+'), ('B', 'B'), ('D+', 'D+'), ('C-', 'C-'), ('A-', 'A-'), ('W', 'W'), ('D', 'D'), ('P', 'P'), ('C', 'C')], default='A', max_length=2),
        ),
    ]
