# Generated by Django 4.2.9 on 2024-02-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_remove_section_instructor_section_instructors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('I', 'I'), ('A-', 'A-'), ('B', 'B'), ('D', 'D'), ('W', 'W'), ('F', 'F'), ('AU', 'AU'), ('B+', 'B+'), ('P', 'P'), ('C+', 'C+'), ('C-', 'C-'), ('B-', 'B-'), ('C', 'C'), ('D+', 'D+')], default='A', max_length=2),
        ),
    ]
