# Generated by Django 4.2.9 on 2024-03-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_remove_coursegetting_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegetting',
            name='median_gpa',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='coursegetting',
            name='st_dev',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coursegetting',
            name='average_gpa',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('C-', 'C-'), ('F', 'F'), ('A-', 'A-'), ('I', 'I'), ('P', 'P'), ('C', 'C'), ('A', 'A'), ('B+', 'B+'), ('D+', 'D+'), ('W', 'W'), ('B-', 'B-'), ('C+', 'C+'), ('AU', 'AU'), ('D', 'D'), ('B', 'B')], default='A', max_length=2),
        ),
    ]
