# Generated by Django 4.2.9 on 2024-03-31 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_coursegetting_median_gpa_coursegetting_st_dev_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.semester'),
        ),
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('C', 'C'), ('A', 'A'), ('A-', 'A-'), ('D', 'D'), ('F', 'F'), ('I', 'I'), ('P', 'P'), ('B+', 'B+'), ('B', 'B'), ('W', 'W'), ('B-', 'B-'), ('C+', 'C+'), ('C-', 'C-'), ('D+', 'D+'), ('AU', 'AU')], default='A', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'section_number', 'section_type', 'semester')},
        ),
    ]
