# Generated by Django 4.2.9 on 2024-03-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_section_unique_together_section_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('D', 'D'), ('B-', 'B-'), ('D+', 'D+'), ('I', 'I'), ('B', 'B'), ('A-', 'A-'), ('W', 'W'), ('C-', 'C-'), ('A', 'A'), ('AU', 'AU'), ('C', 'C'), ('B+', 'B+'), ('P', 'P'), ('F', 'F'), ('C+', 'C+')], default='A', max_length=2),
        ),
    ]
