# Generated by Django 4.2.9 on 2024-03-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_alter_coursegetting_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='time',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('B', 'B'), ('I', 'I'), ('D', 'D'), ('B-', 'B-'), ('A-', 'A-'), ('C', 'C'), ('P', 'P'), ('A', 'A'), ('C+', 'C+'), ('D+', 'D+'), ('B+', 'B+'), ('C-', 'C-'), ('F', 'F'), ('AU', 'AU'), ('W', 'W')], default='A', max_length=2),
        ),
    ]
