# Generated by Django 4.2.9 on 2024-01-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_department_name_and_more'),
        ('courses', '0004_alter_course_department_alter_coursegetting_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('F', 'F'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('I', 'I'), ('W', 'W'), ('A-', 'A-'), ('B+', 'B+'), ('C+', 'C+'), ('C-', 'C-'), ('D+', 'D+'), ('A', 'A'), ('P', 'P'), ('B-', 'B-'), ('AU', 'AU')], default='A', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='coursegetting',
            unique_together={('course', 'section', 'semester', 'instructor')},
        ),
    ]
