# Generated by Django 4.2.9 on 2024-02-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_coursegetting_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('AU', 'AU'), ('F', 'F'), ('C+', 'C+'), ('W', 'W'), ('C', 'C'), ('I', 'I'), ('B', 'B'), ('B-', 'B-'), ('A-', 'A-'), ('C-', 'C-'), ('D+', 'D+'), ('B+', 'B+'), ('A', 'A'), ('P', 'P'), ('D', 'D')], default='A', max_length=2),
        ),
    ]
