# Generated by Django 4.2.9 on 2024-02-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_section_capacity_section_enrolled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('B-', 'B-'), ('C', 'C'), ('AU', 'AU'), ('A', 'A'), ('W', 'W'), ('D', 'D'), ('B+', 'B+'), ('I', 'I'), ('A-', 'A-'), ('D+', 'D+'), ('F', 'F'), ('P', 'P'), ('C+', 'C+'), ('C-', 'C-'), ('B', 'B')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='section',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='enrolled',
            field=models.IntegerField(default=0),
        ),
    ]
