# Generated by Django 4.2.9 on 2024-02-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_coursegetting_grade_alter_section_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('B', 'B'), ('C-', 'C-'), ('I', 'I'), ('C+', 'C+'), ('B-', 'B-'), ('F', 'F'), ('W', 'W'), ('AU', 'AU'), ('D+', 'D+'), ('D', 'D'), ('P', 'P'), ('B+', 'B+'), ('A', 'A'), ('A-', 'A-'), ('C', 'C')], default='A', max_length=2),
        ),
    ]
