# Generated by Django 4.2.9 on 2024-02-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_coursegetting_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('F', 'F'), ('B', 'B'), ('C', 'C'), ('P', 'P'), ('C-', 'C-'), ('I', 'I'), ('A-', 'A-'), ('AU', 'AU'), ('D+', 'D+'), ('D', 'D'), ('B+', 'B+'), ('B-', 'B-'), ('C+', 'C+'), ('W', 'W'), ('A', 'A')], default='A', max_length=2),
        ),
    ]
