# Generated by Django 4.2.9 on 2024-02-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_course_name_alter_coursegetting_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('I', 'I'), ('P', 'P'), ('C-', 'C-'), ('W', 'W'), ('D+', 'D+'), ('B', 'B'), ('AU', 'AU'), ('D', 'D'), ('C+', 'C+'), ('A-', 'A-'), ('F', 'F'), ('B+', 'B+'), ('C', 'C'), ('B-', 'B-'), ('A', 'A')], default='A', max_length=2),
        ),
    ]
