# Generated by Django 4.2.9 on 2024-02-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_coursegetting_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('P', 'P'), ('A', 'A'), ('C', 'C'), ('B', 'B'), ('W', 'W'), ('A-', 'A-'), ('C+', 'C+'), ('AU', 'AU'), ('I', 'I'), ('C-', 'C-'), ('B-', 'B-'), ('D+', 'D+'), ('F', 'F'), ('B+', 'B+'), ('D', 'D')], default='A', max_length=2),
        ),
    ]
