# Generated by Django 4.2.9 on 2024-02-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_coursegetting_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('I', 'I'), ('A', 'A'), ('D+', 'D+'), ('P', 'P'), ('D', 'D'), ('AU', 'AU'), ('C', 'C'), ('B+', 'B+'), ('C+', 'C+'), ('B', 'B'), ('A-', 'A-'), ('W', 'W'), ('F', 'F'), ('C-', 'C-'), ('B-', 'B-')], default='A', max_length=2),
        ),
    ]
