# Generated by Django 4.2.9 on 2024-02-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_course_name_alter_coursegetting_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('C', 'C'), ('P', 'P'), ('F', 'F'), ('C+', 'C+'), ('AU', 'AU'), ('B', 'B'), ('B-', 'B-'), ('D+', 'D+'), ('B+', 'B+'), ('A', 'A'), ('D', 'D'), ('A-', 'A-'), ('W', 'W'), ('C-', 'C-'), ('I', 'I')], default='A', max_length=2),
        ),
    ]
