# Generated by Django 4.2.9 on 2024-02-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_coursegetting_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('C-', 'C-'), ('W', 'W'), ('A-', 'A-'), ('AU', 'AU'), ('D', 'D'), ('I', 'I'), ('B', 'B'), ('F', 'F'), ('B-', 'B-'), ('B+', 'B+'), ('D+', 'D+'), ('P', 'P'), ('C', 'C'), ('A', 'A'), ('C+', 'C+')], default='A', max_length=2),
        ),
    ]
