# Generated by Django 4.2.9 on 2024-03-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_alter_coursegetting_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('C', 'C'), ('W', 'W'), ('D', 'D'), ('D+', 'D+'), ('B+', 'B+'), ('A', 'A'), ('B', 'B'), ('B-', 'B-'), ('C-', 'C-'), ('P', 'P'), ('A-', 'A-'), ('C+', 'C+'), ('I', 'I'), ('AU', 'AU'), ('F', 'F')], default='A', max_length=2),
        ),
    ]
