# Generated by Django 4.2.9 on 2024-03-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_coursegetting_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegetting',
            name='capacity',
        ),
        migrations.AddField(
            model_name='coursegetting',
            name='average_gpa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coursegetting',
            name='section_type',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='coursegetting',
            name='grade',
            field=models.CharField(choices=[('F', 'F'), ('B', 'B'), ('D', 'D'), ('C-', 'C-'), ('A', 'A'), ('C', 'C'), ('A-', 'A-'), ('D+', 'D+'), ('B-', 'B-'), ('I', 'I'), ('C+', 'C+'), ('W', 'W'), ('B+', 'B+'), ('AU', 'AU'), ('P', 'P')], default='A', max_length=2),
        ),
    ]
