# Generated by Django 4.2.9 on 2024-01-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='instructor',
            unique_together={('first_name', 'last_name', 'middle_name')},
        ),
        migrations.AlterUniqueTogether(
            name='major',
            unique_together={('name', 'department')},
        ),
    ]
