# Generated by Django 4.2.9 on 2024-02-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('SMG', 'School of Mining and Geosciences'), ('SSH', 'School of Sciences and Humanities'), ('GSE', 'Graduate School of Education'), ('GSPP', 'Graduate School of Public Policy'), ('NUSOM', 'School of Medicine'), ('SEDS', 'School of Engineering and Digital Sciences'), ('CPS', 'Center for Preparatory Studies'), ('GSB', 'Graduate School of Business')], default='SEDS', max_length=50),
        ),
    ]
