# Generated by Django 4.2.9 on 2024-02-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('GSE', 'Graduate School of Education'), ('CPS', 'Center for Preparatory Studies'), ('NUSOM', 'School of Medicine'), ('GSB', 'Graduate School of Business'), ('GSPP', 'Graduate School of Public Policy'), ('SMG', 'School of Mining and Geosciences'), ('SSH', 'School of Sciences and Humanities'), ('SEDS', 'School of Engineering and Digital Sciences')], default='SEDS', max_length=50),
        ),
    ]
