# Generated by Django 4.2.9 on 2024-02-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('GSPP', 'GSPP | Graduate School of Public Policy'), ('SSH', 'SSH | School of Sciences and Humanities'), ('SEDS', 'SEDS | School of Engineering and Digital Sciences'), ('NUSOM', 'NUSOM | School of Medicine'), ('CPS', 'CPS | Center for Preparatory Studies'), ('GSB', 'GSB | Graduate School of Business'), ('SMG', 'SMG | School of Mining and Geosciences'), ('GSE', 'GSE | Graduate School of Education')], default='SEDS', max_length=50),
        ),
    ]
